/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MomentFactory } from "./MomentFactory";
export type { MomentMetadata } from "./MomentMetadata";
